backend:
  name: git-gateway
  branch: main   # use your default branch

media_folder: "images/uploads"   # where uploaded files go in repo
public_folder: "/images/uploads" # how site refers to them

collections:
  - name: "site"
    label: "Site Settings"
    file: "data/site.json"
    fields:
      - { label: "Church Name", name: "name", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Phone", name: "phone", widget: "string" }
      - { label: "Address", name: "address", widget: "string" }
      - label: "Service Times"
        name: "services"
        widget: "list"
        fields:
          - { label: "Day", name: "day", widget: "string" }
          - { label: "Time", name: "time", widget: "string" }

  - name: "events"
    label: "Events"
    folder: "data/events"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Poster", name: "poster", widget: "image" }
